### PR TITLE
Added Morningstar to HC namespace.

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Use `HighchartsConnectors.Morningstar` instead of `Connectors.Morningstar`.

Related HC PR https://github.com/highcharts/highcharts/pull/22154

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by pawelfus — CHANGES_REQUESTED** [review]
Missing:
- docs update (eg https://github.com/highcharts/connectors-morningstar/blob/main/docs/connectors/morningstar/risk-score.md )
- demos updated (related PR in Core repository)

**Comment by pawelfus** [comment]
Additional request:
Change from `Highcharts` to `HighchartsConnectors`

**Review by pawelfus — CHANGES_REQUESTED** [review]
Prematurely accepted.. the tests are failing. 

```shell

[10:49:03] Start XRay/Breakdown tests ...
[10:49:03] Test breakdown load ... ❌ ERROR.
AssertionError [ERR_ASSERTION]: Connector table should have the expected amount of rows.
    at breakdownLoad (/Users/pawelfus/Projects/connectors-morningstar/tests/XRay/Breakdown.test.ts:48:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runUnitTests (/Users/pawelfus/Projects/connectors-morningstar/tools/tests.ts:165:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by kamil-musialowski** [comment]
@pawelfus , tests should be fine right now. All good on my side 👍

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!

**Pull request merged**
